"use client";

import { useEffect, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { createBrowserSupabaseClient } from "@/lib/supabase/client";
import { formatRupiah } from "@/lib/utils";

type Order = { id: string; order_code: string; table_number: number; customer_name: string | null; status: string; total_amount: number; created_at: string; order_items?: Array<{ menu_item_name: string; quantity: number; subtotal: number }> };
type Reservation = { id: string; reservation_code: string; customer_name: string; whatsapp_number: string; party_size: number; table_number: number; status: string; total_amount: number; start_time: string; notes: string | null; reservation_items?: Array<{ menu_item_name: string; quantity: number; subtotal: number }> };
type Menu = { id: string; name: string; price: number; is_available: boolean; menu_categories?: { name: string } | null };
type Table = { id: string; table_number: number; capacity: number; is_active: boolean };

async function token() { const supabase = createBrowserSupabaseClient(); const { data } = await supabase!.auth.getSession(); return data.session?.access_token || ""; }
async function adminFetch(url: string, options: RequestInit = {}) { const accessToken = await token(); return fetch(url, { ...options, headers: { "Content-Type": "application/json", Authorization: "Bearer " + accessToken, ...(options.headers || {}) } }); }

export function DashboardClient() {
  const [orders, setOrders] = useState<Order[]>([]); const [reservations, setReservations] = useState<Reservation[]>([]);
  useEffect(() => { const supabase = createBrowserSupabaseClient(); if (!supabase) return; supabase.from("orders").select("*,order_items(*)").order("created_at", { ascending: false }).limit(20).then(({ data }) => setOrders((data as Order[]) || [])); supabase.from("reservations").select("*,reservation_items(*)").order("created_at", { ascending: false }).limit(20).then(({ data }) => setReservations((data as Reservation[]) || [])); }, []);
  const today = new Date().toISOString().slice(0, 10); const todayOrders = orders.filter((o) => o.created_at.startsWith(today)); const revenue = [...orders, ...reservations].reduce((sum, entry) => sum + (entry.total_amount || 0), 0);
  const stats = [{ label: "Total orders hari ini", value: todayOrders.length }, { label: "Pending orders", value: orders.filter((o) => o.status === "pending").length }, { label: "Completed orders", value: orders.filter((o) => ["served", "completed"].includes(o.status)).length }, { label: "Pending reservations", value: reservations.filter((r) => r.status.includes("pending")).length }, { label: "Confirmed reservations", value: reservations.filter((r) => r.status === "confirmed").length }, { label: "Revenue estimate", value: formatRupiah(revenue) }];
  return <AdminShellContent title="Dashboard"><div className="grid gap-4 md:grid-cols-3">{stats.map((stat) => <Card key={stat.label} className="p-5"><p className="text-sm text-blackCafe/55">{stat.label}</p><strong className="mt-3 block text-3xl">{stat.value}</strong></Card>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><List title="Recent orders" items={orders.slice(0, 6).map((o) => o.order_code + " · Table " + o.table_number + " · " + o.status)} /><List title="Recent reservations" items={reservations.slice(0, 6).map((r) => r.reservation_code + " · Table " + r.table_number + " · " + r.status)} /></div></AdminShellContent>;
}
function List({ title, items }: { title: string; items: string[] }) { return <Card className="p-5"><h2 className="mb-4 text-xl font-semibold">{title}</h2><div className="grid gap-3 text-sm text-blackCafe/65">{items.length ? items.map((item) => <p key={item} className="rounded-xl bg-warmCafe p-3">{item}</p>) : <p>Belum ada data.</p>}</div></Card>; }
function AdminShellContent({ title, children }: { title: string; children: ReactNode }) { return <><h1 className="mb-6 text-4xl font-semibold">{title}</h1>{children}</>; }

export function OrdersClient() { const [orders, setOrders] = useState<Order[]>([]); const [filter, setFilter] = useState("all"); const [search, setSearch] = useState(""); useEffect(() => { const supabase = createBrowserSupabaseClient(); supabase?.from("orders").select("*,order_items(*)").order("created_at", { ascending: false }).then(({ data }) => setOrders((data as Order[]) || [])); }, []); async function update(id: string, status: string) { await adminFetch("/api/admin/orders/" + id, { method: "PATCH", body: JSON.stringify({ status }) }); setOrders((rows) => rows.map((o) => o.id === id ? { ...o, status } : o)); } const rows = orders.filter((o) => (filter === "all" || o.status === filter) && JSON.stringify(o).toLowerCase().includes(search.toLowerCase())); return <AdminShellContent title="Orders"><Toolbar search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={["all","pending","preparing","served","completed","cancelled"]} /><div className="grid gap-4">{rows.map((o) => <Card key={o.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{o.order_code}</h2><p className="text-sm text-blackCafe/55">Table {o.table_number} · {o.customer_name || "Guest"} · {new Date(o.created_at).toLocaleString("id-ID")}</p><p className="mt-2 font-semibold">{formatRupiah(o.total_amount)}</p></div><select value={o.status} onChange={(e) => update(o.id, e.target.value)} className="rounded-full border border-lineCafe px-4 py-2 text-sm">{["pending","preparing","served","completed","cancelled"].map((s) => <option key={s}>{s}</option>)}</select></div><div className="mt-4 grid gap-2 text-sm text-blackCafe/65">{o.order_items?.map((item) => <p key={item.menu_item_name}>{item.quantity}x {item.menu_item_name}</p>)}</div></Card>)}</div></AdminShellContent>; }

export function ReservationsClient() { const [rows, setRows] = useState<Reservation[]>([]); const [filter, setFilter] = useState("all"); const [search, setSearch] = useState(""); useEffect(() => { createBrowserSupabaseClient()?.from("reservations").select("*,reservation_items(*)").order("created_at", { ascending: false }).then(({ data }) => setRows((data as Reservation[]) || [])); }, []); async function update(id: string, status: string) { await adminFetch("/api/admin/reservations/" + id, { method: "PATCH", body: JSON.stringify({ status }) }); setRows((current) => current.map((r) => r.id === id ? { ...r, status } : r)); } const data = rows.filter((r) => (filter === "all" || r.status === filter) && JSON.stringify(r).toLowerCase().includes(search.toLowerCase())); return <AdminShellContent title="Reservations"><Toolbar search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={["all","pending_payment","pending_confirmation","confirmed","cancelled","completed"]} /><div className="grid gap-4">{data.map((r) => <Card key={r.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{r.reservation_code}</h2><p className="text-sm text-blackCafe/55">{r.customer_name} · WA {r.whatsapp_number} · {r.party_size} orang</p><p className="text-sm text-blackCafe/55">Table {r.table_number} · {new Date(r.start_time).toLocaleString("id-ID")}</p><p className="mt-2 font-semibold">{formatRupiah(r.total_amount)}</p></div><select value={r.status} onChange={(e) => update(r.id, e.target.value)} className="rounded-full border border-lineCafe px-4 py-2 text-sm">{["pending_payment","pending_confirmation","confirmed","cancelled","completed"].map((s) => <option key={s}>{s}</option>)}</select></div><div className="mt-4 grid gap-2 text-sm text-blackCafe/65">{r.reservation_items?.map((item) => <p key={item.menu_item_name}>{item.quantity}x {item.menu_item_name}</p>)}</div></Card>)}</div></AdminShellContent>; }
function Toolbar({ search, setSearch, filter, setFilter, options }: { search: string; setSearch: (v: string) => void; filter: string; setFilter: (v: string) => void; options: string[] }) { return <div className="mb-5 flex flex-col gap-3 md:flex-row"><Input placeholder="Search" value={search} onChange={(e) => setSearch(e.target.value)} /><select value={filter} onChange={(e) => setFilter(e.target.value)} className="h-11 rounded-xl border border-lineCafe px-4 text-sm">{options.map((option) => <option key={option}>{option}</option>)}</select></div>; }

export function MenuAdminClient() { const [rows, setRows] = useState<Menu[]>([]); const [name, setName] = useState(""); const [price, setPrice] = useState(35000); useEffect(() => { createBrowserSupabaseClient()?.from("menu_items").select("*,menu_categories(name)").order("name").then(({ data }) => setRows((data as Menu[]) || [])); }, []); async function add() { const res = await adminFetch("/api/admin/menu", { method: "POST", body: JSON.stringify({ name, price, description: "", categoryId: null, imageUrl: "", isAvailable: true }) }); if (res.ok) location.reload(); } async function toggle(row: Menu) { await adminFetch("/api/admin/menu/" + row.id, { method: "PATCH", body: JSON.stringify({ name: row.name, price: row.price, description: "", categoryId: null, imageUrl: "", isAvailable: !row.is_available }) }); setRows((r) => r.map((item) => item.id === row.id ? { ...item, is_available: !item.is_available } : item)); } return <AdminShellContent title="Menu"><Card className="mb-5 grid gap-3 p-5 md:grid-cols-[1fr_160px_auto]"><Input placeholder="Nama menu" value={name} onChange={(e) => setName(e.target.value)} /><Input type="number" value={price} onChange={(e) => setPrice(Number(e.target.value))} /><Button onClick={add}>Tambah menu</Button></Card><div className="grid gap-3">{rows.map((row) => <Card key={row.id} className="flex items-center justify-between gap-4 p-4"><div><strong>{row.name}</strong><p className="text-sm text-blackCafe/55">{row.menu_categories?.name || "No category"} · {formatRupiah(row.price)}</p></div><Button variant="secondary" onClick={() => toggle(row)}>{row.is_available ? "Nonaktifkan" : "Aktifkan"}</Button></Card>)}</div></AdminShellContent>; }

export function TablesAdminClient() { const [rows, setRows] = useState<Table[]>([]); const [tableNumber, setTableNumber] = useState(13); const [capacity, setCapacity] = useState(2); useEffect(() => { createBrowserSupabaseClient()?.from("cafe_tables").select("*").order("table_number").then(({ data }) => setRows((data as Table[]) || [])); }, []); async function add() { const res = await adminFetch("/api/admin/tables", { method: "POST", body: JSON.stringify({ tableNumber, capacity, isActive: true }) }); if (res.ok) location.reload(); } async function toggle(row: Table) { await adminFetch("/api/admin/tables/" + row.id, { method: "PATCH", body: JSON.stringify({ tableNumber: row.table_number, capacity: row.capacity, isActive: !row.is_active }) }); setRows((r) => r.map((item) => item.id === row.id ? { ...item, is_active: !item.is_active } : item)); } return <AdminShellContent title="Tables"><Card className="mb-5 grid gap-3 p-5 md:grid-cols-[1fr_1fr_auto]"><Input type="number" value={tableNumber} onChange={(e) => setTableNumber(Number(e.target.value))} /><Input type="number" value={capacity} onChange={(e) => setCapacity(Number(e.target.value))} /><Button onClick={add}>Tambah meja</Button></Card><div className="grid gap-3 md:grid-cols-3">{rows.map((row) => <Card key={row.id} className="p-4"><strong>Table {row.table_number}</strong><p className="text-sm text-blackCafe/55">Capacity {row.capacity} · {row.is_active ? "Active" : "Inactive"}</p><Button className="mt-4" variant="secondary" onClick={() => toggle(row)}>{row.is_active ? "Set inactive" : "Set active"}</Button></Card>)}</div></AdminShellContent>; }
